### PR TITLE
[#98091344] Add influxdb datasource to grafana

### PR DESCRIPTION
**Pull request by actionjack**
[Add metrics capture to core components](https://www.pivotaltracker.com/story/show/98091344)

**What**

Extend `Stouts.grafana` ansible role so that it has a helper script that can create a `influxdb 0.9` datasource for `grafana`

**How this PR should be reviewed**

This PR should be reviewed in the following context:

* I would like to create a vagrant machine in order to run and test my `ansilble role`
* I want to create a helper script to allow me to easily create an `influxdb` data source for `grafana`
* I to copy that script somewhere where it can be easily executed.

**How do I test this PR?**

We have provided a vagrant environment to test this PR and it can used as follows:

```
vagrant up
vagrant ssh
cat /usr/local/bin/datasource.sh
ls -al /usr/local/bin/datasource.sh
```

**Who should review this PR**

* Anyone on the core team with the exception of @jimconner who I paired with :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by keymon** [comment]
The PR does the work described: 
 
 * Creates the script.
 * The script is able to run and it does setup grafana properly, we can see it here:
    ```
$ vagrant ssh
$ sudo /usr/local/bin/datasource.sh testdb
Grafana: Data source testdb created

# authenticate grafana
$ curl -qs -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"user":"admin","email":"","password":"admin"}' --cookie-jar /tmp/cookie http://localhost:3000/login | json_pp
{
   "message" : "Logged in"
}

# Check the datasources
$ curl --silent --cookie /tmp/cookie http://localhost:3000/api/datasources | json_pp
[
   {
      "basicAuthPassword" : "",
      "id" : 1,
      "orgId" : 1,
      "name" : "testdb",
      "password" : "testdb",
      "database" : "testdb",
      "isDefault" : true,
      "jsonData" : null,
      "basicAuthUser" : "",
      "basicAuth" : false,
      "user" : "testdb",
      "access" : "proxy",
      "type" : "influxdb",
      "url" : "http://localhost:8086/"
   }
]

```

I got some questions:

 * Shall we change the script to parametrise the user and password for grafana and influx db?

 * This PR only copies this file, but it does not actually call the script. Does it make sense add the script here if it is not called by the role? I got the feeling that the script should be added where ever we setup the datasource. I that case we would have two options: 
     1. add logic in ansible in this role to add the datasource
     2. drop this script in other place (for instance `tsuru-ansible`, or a wrapper role which includes Stouts.grafana as dependency).

**Comment by keymon** [comment]
I found that the script is actually called in [tsuru-ansible](https://github.com/alphagov/tsuru-ansible/commit/5cbaf03f0f78259ae4748c591e436a67a5d75001).

Personally I think it is better to deploy this script to `tsuru-ansible` repository. This way the concern of setting up grafana datasources is all in the same codebase (tsuru-ansible) and we won't need to fork this repository. Additionally, reduces the coupling of the `tsuru-ansible` playbook with this role and allows us to use an alternative method or role to deploy grafana.

**Comment by dcarley** [comment]
> Personally I think it is better to deploy this script to tsuru-ansible repository. This way the concern of setting up grafana datasources is all in the same codebase (tsuru-ansible) and we won't need to fork this repository. Additionally, reduces the coupling of the tsuru-ansible playbook with this role and allows us to use an alternative method or role to deploy grafana.

I agree with this. Would you mind changing, @actionjack @jimconner?

**Comment by jimconner** [comment]
That was a coin-toss between whether it went into the tsuru-ansible playbook or into the Grafana role... (we really did flip a coin)... On one side, it's extra an extra feature/functionality for Grafana which would make sense as an extra for grafana, and therefore belongs in the grafana package.... and on the other side, it's a support script which we're calling from tsusu-ansible to get the datasource added. Happy to move it to tsuru-ansible if that's the consensus.

**Pull request closed without merging**
